[package]
name = "worldtimeapi"
version = "0.1.0"
edition = "2021"
authors = ["Allister Isaiah Harvey <a.i.harvey@icloud.com"]
description = "A simple API for getting the current time in different timezones."
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79" }
reqwest = { version = "0.11.10", features = ["json"] }
chrono = { version = "0.4.19", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
